apiVersion: v2
name: kube-cost-metrics-collector
version: 0.1.9
description: FinOps 360 Kubernetes metrics collector.
type: application
dependencies:
  - name: prometheus
    version: "17.0.2"
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-service-selectors
    version: "1.0.8"
    repository: https://FinOps360HQ.github.io/finops-helm
maintainers:
  - name: finops360
    email: info@finops360.ru
