apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "finops360-k8s-collector.prometheus.server.labels" . | nindent 4 }}
  name: prometheus-server-cert-config
{{ include "finops360-k8s-collector.prometheus.namespace" . | indent 2 }}
data:
{{- if .Values.prometheus.server.caFile }}
  ca.crt: |
{{ .Files.Get .Values.prometheus.server.caFile | indent 4 }}
{{- end  }}
